# Generated by Django 5.2.15 on 2026-08-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_coursegroup_requires_accessibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursegroup",
            name="whatsapp_group_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID du groupe WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="coursegroup",
            name="whatsapp_group_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nom du groupe WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="coursegroup",
            name="whatsapp_group_status",
            field=models.CharField(
                choices=[
                    ("NOT_CREATED", "Non créé"),
                    ("ACTIVE", "Actif"),
                    ("FAILED", "Échec"),
                ],
                default="NOT_CREATED",
                max_length=50,
                verbose_name="Statut du groupe WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="coursegroup",
            name="whatsapp_last_synced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière synchronisation WhatsApp"
            ),
        ),
    ]
