# Generated by Django 5.2.15 on 2026-08-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_whatsapp_group_automation"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppAutomationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_event", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Succès"),
                            ("PARTIAL", "Partiel"),
                            ("FAILED", "Échec"),
                            ("SKIPPED", "Ignoré (condition/cooldown)"),
                            ("DRY_RUN", "Simulation"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("groups_targeted", models.PositiveIntegerField(default=0)),
                ("groups_successful", models.PositiveIntegerField(default=0)),
                ("groups_failed", models.PositiveIntegerField(default=0)),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Exécution d'automatisation WhatsApp",
                "verbose_name_plural": "Exécutions d'automatisations WhatsApp",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="whatsappautomation",
            options={
                "ordering": ["name"],
                "verbose_name": "Automatisation WhatsApp",
                "verbose_name_plural": "Automatisations WhatsApp",
            },
        ),
        migrations.AlterModelOptions(
            name="whatsappmessagetemplate",
            options={
                "ordering": ["name"],
                "verbose_name": "Modèle de message WhatsApp",
                "verbose_name_plural": "Modèles de message WhatsApp",
            },
        ),
        migrations.RenameIndex(
            model_name="whatsappgroup",
            new_name="core_whatsa_group_t_7cc2ef_idx",
            old_name="core_whatsap_group_t_8b8ce1_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappgroup",
            new_name="core_whatsa_automat_5dcd05_idx",
            old_name="core_whatsap_automati_7a23aa_idx",
        ),
        migrations.RenameIndex(
            model_name="whatsappmessagedelivery",
            new_name="core_whatsa_status_a895b5_idx",
            old_name="core_whatsap_status_6e9e4e_idx",
        ),
        migrations.AddField(
            model_name="whatsappautomation",
            name="dry_run_only",
            field=models.BooleanField(
                default=False, verbose_name="Mode simulation uniquement"
            ),
        ),
        migrations.AddField(
            model_name="whatsappautomation",
            name="next_run_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Prochaine exécution"
            ),
        ),
        migrations.AddField(
            model_name="whatsappautomation",
            name="schedule_cron",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Expression de planification (ex: 0 8 * * 1)",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Général"),
                    ("ABSENCE", "Absence"),
                    ("PAYMENT", "Paiement"),
                    ("SESSION", "Séance"),
                    ("EVENT", "Événement"),
                    ("EXAM", "Examen / Test"),
                ],
                default="GENERAL",
                max_length=50,
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="conditions",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Conditions d'exécution (JSON)"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="cooldown_seconds",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Temps de recharge (secondes)"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="enabled",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="last_result",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Dernier résultat"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="last_run_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière exécution"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Nom de l'automatisation"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("GROUP_IDS", "Groupes sélectionnés"),
                    ("GROUP_TYPE", "Type de groupe"),
                    ("ALL_GROUPS", "Tous les groupes éligibles"),
                    ("COURSE", "Groupe de cours"),
                ],
                max_length=20,
                verbose_name="Type de cible",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="target_value",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Valeur de la cible"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.whatsappmessagetemplate",
                verbose_name="Modèle de message",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappautomation",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manuel / À la demande"),
                    ("ANNOUNCEMENT_PUBLISHED", "Annonce publiée"),
                    ("STUDENT_ABSENT", "Élève marqué absent"),
                    ("PAYMENT_OVERDUE", "Rappel paiement en retard"),
                    ("PAYMENT_RECEIVED", "Paiement reçu / Reçu émis"),
                    ("SESSION_CANCELLED", "Séance de cours annulée"),
                    ("SESSION_CHANGED", "Séance de cours modifiée (date/heure/salle)"),
                    ("SCHEDULED", "Planifié / Récurrent"),
                ],
                max_length=30,
                verbose_name="Déclencheur",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="body",
            field=models.TextField(verbose_name="Contenu du modèle"),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Nom du modèle"
            ),
        ),
        migrations.AddField(
            model_name="whatsappautomationrun",
            name="automation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="core.whatsappautomation",
            ),
        ),
        migrations.AddField(
            model_name="whatsappautomationrun",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automation_runs",
                to="core.whatsappmessagejob",
            ),
        ),
    ]
